create database conseg;

use conseg;

create table usuarios(
	id int not null primary key AUTO_INCREMENT,
	nome varchar(100) not null,
	email varchar(150) not null,
	senha varchar(32) not null
);

create table venda(
	id_venda int not null primary key AUTO_INCREMENT,
	nome varchar(32) not null,
	nacionalidade varchar(32) not null,
	idade varchar(32) not null,
  data_nascimento_dados_pessoais varchar(32) not null,
  rg varchar(32) not null,
  cpf varchar(32) not null,
  data_de_expedicao varchar(32) ,
  rua_endereco varchar(32) not null,
  cep_endereco varchar(32) not null,
  cidade_endereco varchar(32) not null,
  estado_endereco varchar(32) not null,
  escolaridade_endereco varchar(32) not null,
  pai_endereco varchar(32)  not null,
  mae_endereco varchar(32)  not null,
  nome_do_conje_endereco varchar(32)  not null,
  data_de_nascimento_endereco varchar(32),
  telefone_endereco varchar(32) not null ,
  telefone_celular varchar(32) not null,
  ponto_refrencia_endereco varchar(32)  not null,
  tempo_residencia_endereco varchar(32)   not null,
  tipo_residencia varchar(32)  not null,
  ocupacao_atividade varchar(32)  not null,
  empresa_atividade varchar(32) not null,
  inicio_atividade varchar(32) not null,
  telefone_empresa_atividade varchar(32) not null ,
  endereco_empresa varchar(32)  not null,
  salario varchar(32) not null ,
  outras_rendas varchar(32) not null ,
  primeira_referencia varchar(32) not null,
  segunda_referencia varchar(32) not null,
  primeiro_telefone varchar(32) not null,
  segundo_telefone varchar(32) not null ,
  email_cliente varchar(32)  not null,
  vendedor varchar(32)  not null,
  lider varchar(32) not null ,
  data_venda varchar(32) not null,
  forma_pagamento varchar(32) ,
  produto varchar(32) not null,
  cor varchar(32)  not null,
  tipo_metal varchar(32)  not null,
  voltagem varchar(32)  not null,
  numeroSerie varchar(32)  not null,
  proximaTrocadeRefil varchar(32) not null);