create database conseg;

use conseg;

create table usuarios(
	id int not null primary key AUTO_INCREMENT,
	nome varchar(100) not null,
	email varchar(150) not null,
	senha varchar(32) not null
);

create table venda(
	id_venda int not null primary key AUTO_INCREMENT,
	nome varchar(32) ,
	sobrenome varchar(32) ,
	idade varchar(32) ,
  data_nascimento_dados_pessoais varchar(32),
  rg varchar(32) ,
  cpf varchar(32) not null,
  data_de_expedicao varchar(32) ,
  rua_endereco varchar(32) ,
  cep_endereco varchar(32),
  cidade_endereco varchar(32),
  estado_endereco varchar(32) ,
  escolaridade_endereco varchar(32) ,
  pai_endereco varchar(32) ,
  mae_endereco varchar(32) ,
  nome_do_conje_endereco varchar(32) ,
  data_de_nascimento_endereco varchar(32),
  telefone_endereco varchar(32) ,
  telefone_celular varchar(32),
  ponto_refrencia_endereco varchar(32) ,
  tempo_residencia_endereco varchar(32)  ,
  tipo_residencia varchar(32) ,
  ocupacao_atividade varchar(32) ,
  empresa_atividade varchar(32),
  inicio_atividade varchar(32) ,
  telefone_empresa_atividade varchar(32) ,
  endereco_empresa varchar(32) ,
  salario varchar(32) ,
  outras_rendas varchar(32) ,
  primeira_referencia varchar(32),
  segunda_referencia varchar(32) ,
  primeiro_telefone varchar(32),
  segundo_telefone varchar(32) ,
  email_cliente varchar(32) ,
  vendedor varchar(32) ,
  lider varchar(32) ,
  data_venda varchar(32),
  forma_pagamento varchar(32) ,
  produto varchar(32) ,
  cor varchar(32) ,
  tipo_metal varchar(32) ,
  voltagem varchar(32) ,
  numeroSerie varchar(32) ,
  proximaTrocadeRefil varchar(32);