<!DOCTYPE html>
 
<html>
  <head>
  <title>Bem Vindo Conseg</title>
  <meta name="description" content="Bem Vindo Conseg">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 

  <link rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
  crossorigin="anonymous">
  
  </head>

 <body>
  <h1> Bem vindo Conseg</h1> 
  <h2> Bem Vindo Conseg</h2><br/>

<form action="Script_do_Formulario.php" method="post">

<!-- DADOS PESSOAIS-->
    Nome: <input type="text" name="nome">

    Sobrenome: <input type="text" name="sobrenome">

    Data de nascimento: <input type="date" name="nascimento">

    CPF: <input type="text" name="cpf" size="9" maxlength="9"> - <input type="text" name="cpf2" size="2" maxlength="2">

    Rg: <input type="text" name="rg" size="13" maxlength="13">

    Data de Expedição: <input type="date" name="expedição">

    Cidade:<input type="text" name="cidade">

    Estado: <td align="left">
    <select name="estado"> 
    <option value="ac">Acre</option> 
    <option value="al">Alagoas</option> 
    <option value="am">Amazonas</option> 
    <option value="ap">Amapá</option> 
    <option value="ba">Bahia</option> 
    <option value="ce">Ceará</option> 
    <option value="df">Distrito Federal</option> 
    <option value="es">Espírito Santo</option> 
    <option value="go">Goiás</option> 
    <option value="ma">Maranhão</option> 
    <option value="mt">Mato Grosso</option> 
    <option value="ms">Mato Grosso do Sul</option> 
    <option value="mg">Minas Gerais</option> 
    <option value="pa">Pará</option> 
    <option value="pb">Paraíba</option> 
    <option value="pr">Paraná</option> 
    <option value="pe">Pernambuco</option> 
    <option value="pi">Piauí</option> 
    <option value="rj">Rio de Janeiro</option> 
    <option value="rn">Rio Grande do Norte</option> 
    <option value="ro">Rondônia</option> 
    <option value="rs">Rio Grande do Sul</option> 
    <option value="rr">Roraima</option> 
    <option value="sc">Santa Catarina</option> 
    <option value="se">Sergipe</option> 
    <option value="sp">São Paulo</option> 
    <option value="to">Tocantins</option> 
   </select>
   
   Escolaridade: <input type="text" name="escolaridade">
   
   Pai:<input type="text" name="pai">
   
   Mãe:<input type="text" name="mãe">

   Nome do Conjuge: <input type="text" name="nome do conjuge">

   Data de nascimento: <input type="date" name="nascimento">

<!-- ENDEREÇO -->

  Rua: <input type="text" name="rua">

  Numero: <input type="text" name="numero" size="4">

  CEP: <input type="text" name="cep" size="5" maxlength="5"> - <input type="text" name="cep2" size="3" maxlength="3">

  Bairro: <input type="text" name="bairro">

  Cidade: <input type="text" name="cidade">

  Estado:<select name="estado"> 
    <option value="ac">Acre</option> 
    <option value="al">Alagoas</option> 
    <option value="am">Amazonas</option> 
    <option value="ap">Amapá</option> 
    <option value="ba">Bahia</option> 
    <option value="ce">Ceará</option> 
    <option value="df">Distrito Federal</option> 
    <option value="es">Espírito Santo</option> 
    <option value="go">Goiás</option> 
    <option value="ma">Maranhão</option> 
    <option value="mt">Mato Grosso</option> 
    <option value="ms">Mato Grosso do Sul</option> 
    <option value="mg">Minas Gerais</option> 
    <option value="pa">Pará</option> 
    <option value="pb">Paraíba</option> 
    <option value="pr">Paraná</option> 
    <option value="pe">Pernambuco</option> 
    <option value="pi">Piauí</option> 
    <option value="rj">Rio de Janeiro</option> 
    <option value="rn">Rio Grande do Norte</option> 
    <option value="ro">Rondônia</option> 
    <option value="rs">Rio Grande do Sul</option> 
    <option value="rr">Roraima</option> 
    <option value="sc">Santa Catarina</option> 
    <option value="se">Sergipe</option> 
    <option value="sp">São Paulo</option> 
    <option value="to">Tocantins</option> 
   </select>

   Telefone: <input type="text" name="telefone">

   Celular: <input type="text" name="celular">

   Ponto Referencia: <input type="text" name="ponto de referencia">

   Tempo de Residencia: <input type="text" name="tempo de residencia">

   Residencia:  <input type="checkbox" name="própia" value="própia">Própia<br>
                <input type="checkbox" name="alugada" value="alugada">Alugada<br>
                <input type="checkbox" name="veiculo3" value="moto">Parentes<br>

   Ocupação: <input type="text" name="ocupação"> 
   
   Empresa/NB: <input type="text" name="empresa/nb">

   Inicio: <input type="date" name="nascimento">

   Endereço da Empresa: <input type="text" name="rua">

   Telefone Da Empresa: <input type="text" name="telefone da empresa">

   Cidade: <input type="text" name="cidade">

   Estado:<select name="estado"> 
    <option value="ac">Acre</option> 
    <option value="al">Alagoas</option> 
    <option value="am">Amazonas</option> 
    <option value="ap">Amapá</option> 
    <option value="ba">Bahia</option> 
    <option value="ce">Ceará</option> 
    <option value="df">Distrito Federal</option> 
    <option value="es">Espírito Santo</option> 
    <option value="go">Goiás</option> 
    <option value="ma">Maranhão</option> 
    <option value="mt">Mato Grosso</option> 
    <option value="ms">Mato Grosso do Sul</option> 
    <option value="mg">Minas Gerais</option> 
    <option value="pa">Pará</option> 
    <option value="pb">Paraíba</option> 
    <option value="pr">Paraná</option> 
    <option value="pe">Pernambuco</option> 
    <option value="pi">Piauí</option> 
    <option value="rj">Rio de Janeiro</option> 
    <option value="rn">Rio Grande do Norte</option> 
    <option value="ro">Rondônia</option> 
    <option value="rs">Rio Grande do Sul</option> 
    <option value="rr">Roraima</option> 
    <option value="sc">Santa Catarina</option> 
    <option value="se">Sergipe</option> 
    <option value="sp">São Paulo</option> 
    <option value="to">Tocantins</option> 
   </select>

   CEP:<input type="text" name="cep" size="5" maxlength="5"> - <input type="text" name="cep2" size="3" maxlength="3">

   Salario: <input type="text" name="salario">

   Outras Rendas: <input type="text" name="outras rendas">

   Referencia 1: <input type="text" name="referencia 1">

   Telefone Ref. 1: <input type="text" name="telefone ref 1">

   Referencia 2: <input type="text" name="referencia 2">

   Telefone Ref. 2: <input type="text" name="telefone ref 2">

   Email Cliente: <input type="text" name="email">

   Vendedor: <input type="text" name="vendedor">

   Lider: <input type="text" name="lider">

   Data Da Venda: <input type="date" name="data da venda">

   Forma De Pagamento:  <input type="checkbox" name="a vista" value="a vista">a vista<br>
                        <input type="checkbox" name="cartão de credito" value="cartão de credito">cartão de credito<br>
                        <input type="checkbox" name="financeira" value="financeira">financeira<br>
                        <input type="checkbox" name="cheque" value="cheque">Cheque<br>

   Produto: <input type="text" name="produto">

   Cor: <input type="text" name="cor">

   Tipo Do Metal: <input type="text" name="tipo do metal">

   Voltagem: <input type="text" name="voltagem">

   N° De Série:<inpnut type="text" name="n° de serie">

   Proxima Troca Do refil: <input type="text" name="proxima">

   Enviar Fomulario: <input type="submit" value="Enviar Formulário">

</form>
 

 </body>
</html>