<!DOCTYPE html>

<html>

<head>
  <title>Bem Vindo Conseg</title>
  <meta name="description" content="Bem Vindo Conseg">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <link rel="stylesheat" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@700&display=swap" rel="stylesheet">

  <link href="public/css/style.css" rel="stylesheet" type="text/css" />
</head>

<body>
  <nav class="navbar navbar-light bg-light">
    <a class=" navbar-brand ml-5" href="#">
      <h1 class="">
        <p>Bem-Vindo a Conseg, cadastre - se.<p>
      </h1>
    </a>
    <div>
      <a href="/painel" class="btn btn-primary fas fa-home mr-5" style="font-size:35px "></a>
      <a href="/sair" class="btn btn-outline-primary fas fa-sign-out-alt mr-2" style="font-size:35px"></a>
    </div>
  </nav>
  <br>

  <form method="post" autocomplete="off" action="/salvarVenda">
    <div class="ml-3 ">
      <h2>
        <p><strong>Dados Pessoais</p></strong>
      </h2>
    </div>
    <div class="border ml-2">
      <div class="p-3  mb-2 bg-transparent text-dark">
        <div class="row col-xl">
          <div class="form-group col-4">
            <label class="" for="textSobrenome">
              <h5>Nome Completo:</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="nome" placeholder="Digite o nome completo" required="required">
          </div>
          <div class="form-group col-4">
            <label class="" for="textSobrenome">
              <h5>Nacionalidade: </h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="nacionalidade" placeholder="Digite sua nacionalidade" required="required">
          </div>
        </div>
        <div class="row col-xl">
          <div class="form-group col-1">
            <label class="" for="textSobrenome">
              <h5>Idade: </h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="idade" placeholder="Idade" maxlength="2" required="required">
          </div>
          <div class="form-group col-4">
            <label class="" for="textSobrenome">
              <h5> Data de nascimento: </h5>
            </label>
            <input class="form-control form-control-sm col-5" type="date" name="dataDeNascimentoDadosPessoais" required="required">
          </div>
        </div>
        <div class="row col-xl">
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>RG :</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="rg" placeholder="Digite o RG" maxlength="11" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5> CPF : </h5>
            </label>
            <input class="form-control form-control-sm " type="text" name="cpf" size="11" maxlength="14" placeholder="Digite o CPF" required="required">
          </div>
          <div class="form-group col-4">
            <label class="" for="textSobrenome">
              <h5> Data de Expedição: </h5>
            </label>
            <input class="form-control form-control-sm col-5" type="date" name="dataDeExpedicao" required="required">
          </div>
        </div>
      </div>
    </div>
    </div>
    <p>
      <div class="ml-3">
        <h2>
          <p><strong>Endereço</p></strong>
        </h2>
      </div>
      <div class="border ml-2">
        <br>
        <div class="row col-xl">
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Rua:</h5>
            </label>
            <input class="form-control form-control-sm col-12" type="text" name="ruaEndereco" placeholder="Digite a Rua com o Numero" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>CEP:</h5>
            </label>
            <input class="form-control form-control-sm " type="text" name="cepEndereco" placeholder="Digite o CEP" maxlength="9" required="required">
          </div>

          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Cidade:</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="cidadeEndereco" placeholder="Digite a Cidade" required="required">
          </div>
        </div>

        <br>

        <div class="row col-xl">
          <div class="form-group ml-3">
            <label class="" for="textSobrenome">
              <h5>Estado:</h5>
            </label>
            <select class="form-group form-group-sm" name="estadoEndereco">
              <option value="ac">Acre</option>
              <option value="al">Alagoas</option>
              <option value="am">Amazonas</option>
              <option value="ap">Amapá</option>
              <option value="ba">Bahia</option>
              <option value="ce">Ceará</option>
              <option value="df">Distrito Federal</option>
              <option value="es">Espírito Santo</option>
              <option value="go">Goiás</option>
              <option value="ma">Maranhão</option>
              <option value="mt">Mato Grosso</option>
              <option value="ms">Mato Grosso do Sul</option>
              <option value="mg">Minas Gerais</option>
              <option value="pa">Pará</option>
              <option value="pb">Paraíba</option>
              <option value="pr">Paraná</option>
              <option value="pe">Pernambuco</option>
              <option value="pi">Piauí</option>
              <option value="rj">Rio de Janeiro</option>
              <option value="rn">Rio Grande do Norte</option>
              <option value="ro">Rondônia</option>
              <option value="rs">Rio Grande do Sul</option>
              <option value="rr">Roraima</option>
              <option value="sc">Santa Catarina</option>
              <option value="se">Sergipe</option>
              <option value="sp">São Paulo</option>
              <option value="to">Tocantins</option>
            </select>
          </div>
          <div class="form-group">
            <label class="ml-3" for="textSobrenome">
              <h5>Escolaridade:</h5>
            </label>
            <select name="escolaridadeEndereco">
              <option value="Fundamental">Fundamental</option>
              <option value="Médio">Médio</option>
              <option value="Superior incompleto">Superior incompleto</option>
              <option value="Superior Completo">Superior Completo</option>
            </select>
          </div>
        </div>
        <div class="row col-xl">
          <div class="form-group col-3  ">
            <label class="" for="textSobrenome">
              <h5>Nome do Pai:</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="paiEndereco" placeholder="Digite o nome do Pai" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Nome da Mãe:</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="maeEndereco" placeholder="Digite o nome da Mãe" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Nome do Conje:</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="nomeDoConjeEndereco" placeholder="Digite o nome do Conje" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5> Data de nascimento: </h5>
            </label>
            <input class="form-control form-control-sm col-8 " type="date" name="dataDeNascimentoEndereco" require>
          </div>
        </div>
        <div class="row col-xl">
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Telefone :</h5>
            </label>
            <input class="form-control form-control-sm col-12" type="text" name="telefoneEndereco" placeholder="Digite seu Telefone" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Celular :</h5>
            </label>
            <input class="form-control form-control-sm col-8" type="text" name="telefoneCelular" placeholder="Celular" required="required">
          </div>
        </div>
        <div class="row col-xl">
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Ponto de Referencia :</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="pontoDeRefrenciaEndereco" placeholder="Ponto de Referencia" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Tempo de Residencia :</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="tempoDeResidenciaEndereco" placeholder="Tempo Residencia" required="required">
          </div>
          <div class="form-group col-5">
            <label class="ml-5" for="textSobrenome">
              <h5>
                <p>Residencia:</p>
              </h5>
            </label>
            <input class="ml-2" type="checkbox" name="tipoResidencia" value="propria"> Própia
            <input class="ml-2" type="checkbox" name="tipoResidencia" value="alugada"> Alugada
            <input class="ml-2" type="checkbox" name="tipoResidencia" value="parentes"> Parentes
          </div>
        </div>
      </div>
      </div>
      <br>
      <div class="ml-3">
        <h2>
          <p><strong>Atividades Exercidas</p></strong>
        </h2>
      </div>
      <div class="border ml-2">
        <br>
        <div class="row col-xl">
          <div class="form-group col-4">
            <label class="" for="textSobrenome">
              <h5>Ocupação:</h5>
            </label>
            <input class="form-control form-control-sm col-10" type="text" name="ocupacaoAtividade" placeholder="Oficio" required="required">
          </div>
          <div class="form-group col-4">
            <label class="" for="textSobrenome">
              <h5>Empresa:</h5>
            </label>
            <input class="form-control form-control-sm col-12" type="text" name="empresaAtividade" placeholder="Empresa" required="required">
          </div>
          <div class="form-group col-3 ml-4">
            <label class="" for="textSobrenome">
              <h5> Inicio:</h5>
            </label>
            <input class="form-control form-control-sm col-7" type="date" name="inicioAtividade" placeholder="Ocupação" required="required">
          </div>
        </div>
        <div class="row col-xl">
          <div class="form-group col-4">
            <label class="" for="textSobrenome">
              <h5>Tel. Empresa:</h5>
            </label>
            <input class="form-control form-control-sm col-10" type="text" name="telefoneDaEmpresaAtividade" placeholder="Telefone" required="required">
          </div>
          <div class="form-group col-4">
            <label class="" for="textSobrenome">
              <h5>Endereço Empresa:</h5>
            </label>
            <input class="form-control form-control-sm col-12" type="text" name="enderecoDaEmpresa" placeholder="Empresa" required="required">
          </div>
        </div>
        <div class="row col-xl">
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Salário:</h5>
            </label>
            <input class="form-control form-control-sm col-10" type="text" name="salario" placeholder="Sálário" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Outras rendas:</h5>
            </label>
            <input class="form-control form-control-sm col-12" type="text" name="outrasRendas" placeholder="Rendas" required="required">
          </div>
        </div>
      </div>
      <br>
      <div class="ml-3">
        <h2>
          <p><strong>Dados do Contato</p></strong>
        </h2>
      </div>
      <div class="border ml-2">
        <br>
        <div class="row col-xl">
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Referencia 1:</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="primeiraReferencia" placeholder="Nome de Referencia 1" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Referencia 2:</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="segundaReferencia" placeholder="Nome de Referencia 2" required="required">
          </div>
        </div>
        <div class="row col-xl">
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Tel. Referencia 1:</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="primeiroTelefone" placeholder="Telefone Referencia 1" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Tel.Referencia 2:</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="segundoTelefone" placeholder="Telefone Referencia 2" required="required">
          </div>
        </div>
        <div class="row col-xl">
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>E-mail Cliente:</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="emailCliente" placeholder="Telefone Vendedor" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Vendedor:</h5>
            </label>
            <input class="form-control form-control-sm" type="text" name="vendedor" placeholder="Nome do Vendedor" required="required">
          </div>
        </div>
      </div>
      <br>
      <div class="ml-3">
        <h2>
          <p><strong>Dados da Venda</p></strong>
        </h2>
      </div>
      <div class="border ml-2">
        <br>
        <div class="row col-xl">
          <div class="form-group col-4">
            <label class="" for="textSobrenome">
              <h5>Lider:</h5>
            </label>
            <input class="form-control form-control-sm col-8" type="text" name="lider" placeholder="Lider Venda" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Data da venda:</h5>
            </label>
            <input class="form-control form-control-sm col-6" type="date" name="dataDaVenda" required="required">
          </div>
        </div>
        <br>
        <div class="row col-xl">
          <div class="form-group">
            <label class="ml-3" for="textSobrenome">
              <h5>Forma De Pagamento:</h5>
            </label>
            <input class="ml-2" type="checkbox" name="formaDePagamento" value="A vista"> A Vista
            <input class="ml-2" type="checkbox" name="formaDePagamento" value="cartaoCredito"> Cartão de Credito
            <input class="ml-2" type="checkbox" name="formaDePagamento" value="financeira"> Financeira
            <input class="ml-2" type="checkbox" name="formaDePagamento" value="cheque"> Cheque
          </div>
        </div>
        <br>
        <div class="row col-xl">
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Produto:</h5>
            </label>
            <input class="form-control form-control-sm col-12" type="text" name="produto" placeholder="Produto" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Cor:</h5>
            </label>
            <input class="form-control form-control-sm col" type="text" name="cor" placeholder="Cor produto" required="required">
          </div>
        </div>
        <div class="row col-xl">
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Tipo de Metal:</h5>
            </label>
            <input require class="form-control form-control-sm" type="text" name="tipoDoMetal" placeholder="Tipo do Metal" required="required">
          </div>
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>Voltagem:</h5>
            </label>
            <input class="form-control form-control-sm " type="text" name="voltagem" placeholder="Voltagem" required="required">
          </div>
        </div>

        <div class="row col-xl">
          <div class="form-group col-3">
            <label class="" for="textSobrenome">
              <h5>N° De Série:</h5>
            </label>
            <input class="form-control form-control-sm col-12" type="numeroSerie" name="numeroSerie" placeholder="N° Série" required="required">
          </div>
          <div class="form-group col-4">
            <label class="" for="textSobrenome">
              <h5>Proxima Troca refil:</h5>
            </label>
            <input class="form-control form-control-sm col-6" type="date" name="proximaTrocadeRefil" placeholder="Empresa" required="required">
          </div>
        </div>


        <div class="form-group">
          <input class="btn btn-primary btn-lg ml-3" type="submit" value="Enviar Formulário">
        </div>




  </form>


</body>

</html>