<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
	integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
	crossorigin="anonymous">

    <title>Bem vindo a Conseg</title>

</head>
<body>
	<!DOCTYPE html>
<head>
  <meta charset="UTF-8" />
   <title>Revenda Coseg</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <link rel="stylesheet" type="text/css" href="style.css" />
</head>
<body>

  
  <div class="text-center" >
    <a class="links" id="paracadastro"></a>
    <a class="links" id="paralogin"></a>

    <br>
    <br>
    <div class="content">      
      <!--FORMULÁRIO DE LOGIN-->
      <div id="login">
        <form method="post" action="/login"> 
          <h1>Login</h1> 
  
          <p> 
            <label for="email_login">Seu Login</label>
            <input id="email_login" name="email" required="required" type="text" placeholder="ex. Login" /> 
          </p>

          <p> 
            <label for="email_login">Sua senha</label>
            <input id="email_login" name="senha" required="required" type="password" placeholder="ex. senha" /> 
          </p>
           
          <p> 
            <input type="checkbox" name="manterlogado" id="manterlogado" value="" /> 
            <label for="manterlogado">Manter-me logado</label>
          </p>
           
          <p> 
            <input type="submit" value="Logar" /> 
          </p>
           
        </form>
      </div>
 
</body>
</html>

